### ISSUE TITLE
CLIPasswordSDK stopped working in 1.2.0

### ISSUE THREAD

**Issue by cbarga** [infamousjoeg/pyaim#21]
Getting an error when trying to use the CLIPasswordSDK method.

[root@lncd906 sdk]# ls -l /opt/CARKaim/sdk/clipasswordsdk
-rwxr-xr-x. 1 root bin 6903152 Jun 13 03:38 /opt/CARKaim/sdk/clipasswordsdk

[root@lncd906 sdk]# python3
Python 3.6.8 (default, Jun 11 2019, 15:15:01)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyaim import CLIPasswordSDK
>>> aimcp = CLIPasswordSDK('/opt/CARKaim/sdk/clipasswordsdk')
>>> response = aimcp.GetPassword(appid='APP_CyberArkDAP_QA',safe='DAP_Automation',objectName='dap_automation-github')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyaim/aimcp.py", line 63, in GetPassword
    response = subprocess.run(query, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/CARKaim/sdk/clipasswordsdk GetPassword -p AppDescs.AppID=APP_CyberArkDAP_QA -p Query=safe=DAP_Automation;object=dap_automation-github; -p RequiredProps=* -o Password': '/opt/CARKaim/sdk/clipasswordsdk GetPassword -p AppDescs.AppID=APP_CyberArkDAP_QA -p Query=safe=DAP_Automation;object=dap_automation-github; -p RequiredProps=* -o Password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyaim/aimcp.py", line 68, in GetPassword
    raise Exception(e)
Exception: [Errno 2] No such file or directory: '/opt/CARKaim/sdk/clipasswordsdk GetPassword -p AppDescs.AppID=APP_CyberArkDAP_QA -p Query=safe=DAP_Automation;object=dap_automation-github; -p RequiredProps=* -o Password': '/opt/CARKaim/sdk/clipasswordsdk GetPassword -p AppDescs.AppID=APP_CyberArkDAP_QA -p Query=safe=DAP_Automation;object=dap_automation-github; -p RequiredProps=* -o Password'
>>>

[root@lncd906 sdk]# /opt/CARKaim/sdk/clipasswordsdk GetPassword -p AppDescs.AppID=APP_CyberArkDAP_QA -p Query="Safe=DAP_Automation;Object=dap_automation-github" -o PassProps.UserName
clb10

As you can see from the first command, the executable exists.  From the last command, you can see that clipasswordsdk works from the command line.  CLIPasswordSDK method worked in the previous version (1.1.3)

**Comment by infamousjoeg** [comment]
Was the new version released able to fix your issues?  I'm able to test successfully now.

**Comment by cbarga** [comment]
Yes, 1.2.7 works as expected.  Thank you!
