### ISSUE TITLE
Virtual UserName auth issue

### ISSUE THREAD

**Issue by smill59** [infamousjoeg/pyaim#24]
I am able to retrieve the credential information using the object name:

from pyaim import CCPPasswordREST

aimccp = CCPPasswordREST('https://aimdev.mycompany.com', verify=True) # set verify=False to ignore SSL

service_status = aimccp.check_service()
print(service_status)

if service_status == 'SUCCESS: AIMWebService Found. Status Code: 200':
    response = aimccp.GetPassword(appid='APP-DV-Test',safe='S-GEN-Test',objectName='APITest',reason='Reason message')
    print('Full Python Object: {}'.format(response))
    print('UserName: {}'.format(response['UserName']))
    print('Password: {}'.format(response['Content']))
else:
    raise Exception(service_status)

However when I use the same code, but use username to pass the Virtual UserName, I get an error.

from pyaim import CCPPasswordREST

aimccp = CCPPasswordREST('https://aimdev.mycompany.com', verify=True) # set verify=False to ignore SSL

service_status = aimccp.check_service()
print(service_status)

if service_status == 'SUCCESS: AIMWebService Found. Status Code: 200':
    response = aimccp.GetPassword(appid='APP-DV-Test',safe='S-GEN-Test',username='VIRT_API_Test',reason='Reason message')
    print('Full Python Object: {}'.format(response))
    UserName = ('UserName: {}'.format(response['UserName']))
    print (UserName)
    AIMPass = ('Password: {}'.format(response['Content']))
    print (AIMPass)
    #print('UserName: {}'.format(response['UserName']))
    #print('Password: {}'.format(response['Content']))
else:
    raise Exception(service_status)

Full Python Object: {'ErrorCode': 'APPAP004E', 'ErrorMsg': 'Password object matching query [UserName=VIRT_API_Test;Safe=S-GEN-Test] was not found (Diagnostic Info: 5). Please check that there is a password object that answers your query in the Vault and that both the Provider and the application user have the appropriate permissions needed in order to use the password.'}

**Comment by infamousjoeg** [comment]
Via E-mail you had stated that using CCP works, but now the issue lies with CLIPasswordSDK?

Can you please post the error response from CLIPasswordSDK if that's the case?

**Comment by smill59** [comment]
I am using the CCP to connect in both cases.  I am able to retrieve credentials using the object name, but I receive the error using the same app id/safe and the virtual user name instead of object name

**Comment by infamousjoeg** [comment]
@smill59 I wanted to let you know that I am and have been working on this.  I'm working with PM directly in making sure this follows best practices when utilizing Dual Accounts and dealing with their potential Active/Inactive status.

I will keep this Issue updated with progress and am hoping to have this resolved by next week.

Thank you so much for your patience!

**Comment by infamousjoeg** [comment]
![image](https://user-images.githubusercontent.com/1924063/74468592-12abc100-4e69-11ea-81d8-11176d47e0bd.png)

I have just pushed pyaim v1.2.8 to Pypi.org that supports Dual Accounts as reflected in the above screenshot.

Please report back @smill59 if that fixes your issue so I can close this out.

**Comment by smill59** [comment]
@infamousjoeg ...thanks much! I was able to test successfully. I appreciate all your help.
