### ISSUE TITLE
Handling passwords with comma ","

### ISSUE THREAD

**Issue by sujeethav** [infamousjoeg/pyaim#34]
In the aimcpp.py the response returned from sub process call is split by comma ",". So if there is comma in a password then the output returned is wrong.

**Comment by infamousjoeg** [comment]
@sujeethav is it out of the question to add `,` to the `PasswordForbiddenChars` list of the Platform on the account in question?

![image](https://user-images.githubusercontent.com/1924063/87615082-d6161700-c6df-11ea-9611-eb73df105618.png)
