### ISSUE TITLE
Support for multiple Server URLs

### ISSUE THREAD

**Issue by ipv6freely** [infamousjoeg/pyaim#42]
**Is your feature request related to a problem? Please describe.**
It would be really beneficial to be able to attempt to connect to multiple backup URLs if the first one fails, with a fairly short timeout. 

**Describe the solution you'd like**
Implement some sort of timeout before trying a backup URL

**Describe alternatives you've considered**
I could build this logic into my script using pyaim, but that woudn't let me specify the timeout for the connection attempt.

**Additional context**
N/A

**Comment by mlarivie** [comment]
Why not use the requests module to check for the 200 status code and response time, then kick off the aim code? This is typically how load balancers check the backend hosts.

**Comment by infamousjoeg** [comment]
@ipv6freely Would adding a timeout parameter help alleviate this problem?

**Comment by infamousjoeg** [comment]
Implementing timeout parameter on PR #70
