### ISSUE TITLE
Passing PyAIM a certificate P12 file or any other of authentication method

### ISSUE THREAD

**Issue by tronatore** [infamousjoeg/pyaim#46]
**Is your feature request related to a problem? Please describe.**
No problem, except that I cannot make it work with a .p12 file or similar. I understand, based upon cyberark's documentation and support personnel, that in order to use cyberark's Applications, a machine or certificate's serial number must be used for authentication purposes. I have tried only with powershell (by using Invoke-Method, "-Certificate" flag is required for passing the variable holding the authentication file (.p12)).

As part of the examples listed, is there any which shows how to pass the certificate's serial number or any other authentication in order to retrieve a password?

**Describe the solution you'd like**
No solution proposed.

**Describe alternatives you've considered**

**Additional context**
I would appreciate your support and thank you for the time you put into these programs.

**Comment by dvdangelo33** [comment]
I added some updates to include client certificate auth,

**Comment by infamousjoeg** [comment]
Related #62 - Support for client certificates has been added here
